### ISSUE TITLE
Puppet error "Error: Could not find command 'curl'"

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/pilots#8]
I am getting this error inside the Dockerfile.

**Comment by xeviscc** [comment]
The following lines in puppet make use of curl in order to get the file. 

``` puppet
tomcat::instance { 'tomcat8':
  catalina_base => '/opt/apache-tomcat/tomcat8',
  source_url    => 'http://apache.mirror.iphh.net/tomcat/tomcat-8/v8.0.29/bin/apache-tomcat-8.0.29.tar.gz'
}
```

and so it fails. It is needed to add the following line in the Dockerfile:

``` Dockerfile
RUN apt-get -yq install curl
```

**Comment by j-fuentes** [comment]
We cannot add every dependency on the base images.

You can install curl in the manifest, with puppet, or also in a dockerfile based on the base image.

I've used this module: https://forge.puppetlabs.com/puppetlabs/apt for installing packages from puppet. You can add that module to the `puppetfile` and just use it to install curl.

But, since curl is a very common package, we can add it to the base.

What do you think is better?

**Comment by xeviscc** [comment]
Maybe it would be better to add it on the base image as it is a very common and not huge tool.

**Comment by j-fuentes** [comment]
Perfect, I'm on it.

**Comment by j-fuentes** [comment]
Done.

Curl is now installed on all the base images.

Please, update your local copy of the image and download it again from dockerhub.
